train:
  batch_size: -1
  learning_rate: 0.001
  epochs: 100
  optimizer: 'AdamW'
  quant_learning_rate: 0.001

losses:
  # cross entropy loss
  cross_entropy_weight: 1.0
  cross_entropy_temperature: 1.0
  # distance loss
  entropy_weight: 0.02
  mindist_weight: 10.0
  # Repulsion loss
  repulsion_loss_weight: 0.1
  repulsion_loss_margin: 0.0001

  use_softmin_grads : False

model:
  input_dim: 11
  output_dim: 1
  proto_count_per_dim: 50

quantizer:
  quantizer_type: 'voronoi' # it can take "voronoi", "grid", "kdtree"
  

log_dir: './logs'
dataset_path: './data/raw/White_Wine/all_data.npy'
seed: 1
