train:
  batch_size: -1
  learning_rate: 0.001
  epochs: 149
  optimizer: 'Adam'
  num_workers: 2
  quant_learning_rate: 0.01

losses:
  # cross entropy loss
  cross_entropy_weight: 1.0
  cross_entropy_temperature: 1.0
  # distance loss
  entropy_weight: 0.0
  mindist_weight: 1.0
  # Repulsion loss
  repulsion_loss_weight: 0.1
  repulsion_loss_margin: 0.01

  use_softmin_grads : False
model:
  input_dim: 1
  output_dim: 1
  proto_count_per_dim: 50

quantizer:
  quantizer_type: 'voronoi' # it can take "voronoi", "grid", "kdtree"
  add_remove_usage_mode: 'softlabelbased' #"bincountbased", "softlabelbased"
  add_remove_every_n_epoch: 50
  proto_split_density_threshold: 0.01
  proto_remove_density_threshold: 0.001
  
eval:
  conformal_mode : "prob_th" # dens_th | prob_th

log_dir: './logs'
dataset_path: './data/raw/Unconditional_1d_data/seed_0/all_data.npy'
seed: 42
device: 'cuda:0'
verbose: false