batch_size: -1
learning_rate: 0.001
epochs: 100
optimizer: 'Adam'
loss_fn: 'CrossEntropyLoss'
input_dim: 1
output_dim: 2
proto_count_per_dim: 50
log_dir: './logs'
dataset_path: './data/raw/Unconditional_2d_data/all_data.npy'
